### PR TITLE
Bump @primer/gatsby-theme-doctocat from 3.1.1 to 4.0.0

### PR DESCRIPTION
**Pull request by josepmartins**
Bump `Doctocat` theme to v4 for a consistent reader experience when navigating between different implementation doc sites.

- Bump to PRC v35 and Doctocat v4
- Remove deprecated `Grid`, `ButtonOutline`, `Flex` and `BorderBox` components. Use `Box` component instead
- Adjust old `LabelGroup` and `Label` to new variant/styles as a temporary solution for the Rails/Figma/React links in the header. We might need to include these links inside the `Layout` component in `Doctocat`.
- Adjust the `Heading` component to use `h4` tags

Screenshot 2022-08-08 at 16 51 56

**Reference**
- https://github.com/github/primer/issues/1192
- https://github.com/primer/design/pull/266

### CODE REVIEW

**Comment by josepmartins** [comment]
Preview: https://primer-ae7d2f7bb9-26441320.drafts.github.io/

**Review by langermank — COMMENTED** [review]
Noticing a few visual regressions we might want to address:

So happy to see the underlined links finally! It seems like most of the anchor link headings don't have underlines. Do we know if the links on the index page need them? If they do maybe we want to remove the horizontal line break.

index page heading sized links with underlines

This video section on the Forms guidelines looks a little funky, but it does in production as well. Maybe @mperrotti would want to take a look at that in a followup to make sure the videos are uniform in size/easy to see 😄 

form interface guideline inline validation video layout issues

**Comment by josepmartins** [comment]
@langermank good point. Seems that these header links don't use the underlined styles, I just removed them and checked all the index pages.

@mperrotti I made a fix to the Form video layout, based on what you did on the `SegmentedControl` guidelines (just missing a `flex-shrink: 0` Box wrapper

Screenshot 2022-08-10 at 16 34 21

**Comment by josepmartins** [comment]
@langermank In this case I rather move on with this and later define a better semantic/structure for headings with/without links, as the PR has a lot of changes already.

**Review by langermank — APPROVED** [review]
Thank you!!

**Pull request merged**
