### PR TITLE
Automate figma docs from json

### PR DESCRIPTION
**Pull request by lukasoppermann**
This PR extracts data from the new [figma docgen](https://github.com/primer/figma-library-docgen) npm package to generate figma documentation:

- [x] Create a list of component .mdx pages to show figma content.
  - [x] Automate playground including variants and component props
  - [x] Generate a table of component props and variants
  - [x] Add custom examples section
       
       
Screenshot 2023-02-02 at 14 12 56

This component documentation is temporarily stored in the `content/guides/figma/components` files.mdx pages pending to be moved once we release a `/component/:id` format page.

### CODE REVIEW

**Comment by danielguillan** [comment]
Thumbnails are now fixed with the latest version of `figma-library-docgen`.

**Comment by ollie-iterators** [comment]
> This is a working version of the docs. However there are still some issues:
> 
> * [x]  @josepmartins I get an error because of a missing unique keyProp for `FigmaPropertyOverview` and I don't get it solved. The culprit are the values in the overview table. Can you have a look?
> * [x]  @danielguillan is working on a tough issue to get post variant and component properties into the thumbnails. Until this is solved most previews don't show anything
> * [ ]  some components in the figma primer web library need to get `[[PROP_OVERVIEW]]` slides to work

What components need to get [[PROP_OVERVIEW]] slides to work?

**Comment by lukasoppermann** [comment]
@ollie-iterators I think all need them now. It is hard to detect which ones need them and which not. Technically they are only necessary for ones with component props but that would require complicated code.

**Comment by josepmartins** [comment]
Closing this as completed here: https://github.com/primer/design/pull/404

**Pull request closed without merging**
