### PR TITLE
Use Node v18.18.2 LTS (Iron)

### PR DESCRIPTION
**Pull request by mxdvl**
### What?

Bump Node to v18.18.2 LTS Iron, which has [maintenance support until the end of April 2025](https://github.com/nodejs/release#release-schedule).

### Why?

[Node 16 has reached end-of-life in September 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/)

### CODE REVIEW

**Comment by camertron** [comment]
Hey @mxdvl, thanks for this! Could you also update the node version in the various workflow configs as well, eg [here](https://github.com/primer/design/blob/063f781b2f79aaa9f07f8f0a0b4be9b67c4f447b/.github/workflows/ci.yml#L10C22-L10C22)?

**Comment by mxdvl** [comment]
> Hey @mxdvl, thanks for this! Could you update the node version in the various workflow configs as well, eg [here](https://github.com/primer/design/blob/063f781b2f79aaa9f07f8f0a0b4be9b67c4f447b/.github/workflows/ci.yml#L10C22-L10C22)?

Good shout, I hadn't spotted them! I'll probably [refactor to using the `node-version-file` config](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file) to keep things automatically in sync in the future.

**Review by camertron — APPROVED** [review]
Ok, I _think_ these changes are ok. It's hard to know since our CI doesn't run for forks. I'm going to merge for now and revert later if necessary.

**Comment by camertron** [comment]
Sadly the [build failed](https://github.com/primer/design/actions/runs/7039103228/job/19157437091) but that's because of a syntax error introduced by https://github.com/primer/design/pull/682. The node upgrade itself is fine. I pushed a fix straight to main 🤠 and [things look good](https://github.com/primer/design/actions/runs/7039157126/job/19157599793).

**Comment by mxdvl** [comment]
> Sadly the [build failed](https://github.com/primer/design/actions/runs/7039103228/job/19157437091) but that's because of a syntax error introduced by https://github.com/primer/design/pull/682. The node upgrade itself is fine. I pushed a fix straight to main 🤠 and [things look good](https://github.com/primer/design/actions/runs/7039157126/job/19157599793).

Very puzzled as [“nullish coalescing” is marked as supported since Node 14.5](https://node.green/#ES2020-features--nullish-coalescing-operator-----) 🤔

**Pull request merged**
